config/routes.rb
Rails.application.routes.draw do
  root "manufacturing_statuses#index"
  resources :manufacturing_statuses, only: [:index, :new, :create, :show, :update] do
  end
  resources :brands, only: [:index, :new, :create] do
    collection do
      get 'search'
    end
  end
  resources :materials, only: [:index] do
  end
  resources :cigarette_shreds, only: [:index, :new, :create] do
  end
  resources :paper_rolls, only: [:index, :new, :create] do
  end
  resources :small_boxes, only: [:index, :new, :create] do
  end
  resources :filters, only: [:index, :new, :create] do
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :cigarette_shred
  belongs_to :small_box
  belongs_to :paper_roll
  belongs_to :filter
  has_many :manufacturing_statuses

  def self.search(search)
    if search
      Brand.where('name LIKE(?)', "#{search}%")
      #Brand.where(['name LIKE ? OR cigarette_shred_id LIKE ? OR paper_roll_id LIKE ? OR small_box_id LIKE ? OR filter_id  LIKE ?', "#{search}%", "#{search}%", "#{search}%", "#{search}%", "#{search}%"])
    else
      Brand.all
    end
  end
end

app/models/cigarette_shred.rb
class CigaretteShred < ApplicationRecord
  has_many :brands
end

app/models/filter.rb
class Filter < ApplicationRecord
  has_many :brands
end

app/models/manufacturing_status.rb
class ManufacturingStatus < ApplicationRecord
  belongs_to :brand
end

app/models/paper_roll.rb
class PaperRoll < ApplicationRecord
  has_many :brands
end

app/models/small_box.rb
class SmallBox < ApplicationRecord
  has_many :brands
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    Brand.create(brand_params)
    redirect_to brands_path
  end

  def search
    @brands = Brand.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end

  def brand_params
    params.require(:brand).permit(:name, :cigarette_shred_id, :small_box_id, :paper_roll_id, :filter_id)
  end
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  def index
    @filters = Filter.all
    @filter = Filter.new
  end

  def create
    @filter = Filter.create(filter_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def filter_params
    params.require(:filter).permit(:name)
  end
end

app/controllers/manufacturing_statuses_controller.rb
class ManufacturingStatusesController < ApplicationController
  def index
    @manufacturingstatuses = ManufacturingStatus.all
  end

  def new
    @manufacturingstatus = ManufacturingStatus.new
  end

  def create
    @manufacturingstatus = ManufacturingStatus.create(manufacturingstatus_params)
    redirect_to root_path
  end

  def show
    @manufacturingstatuses = ManufacturingStatus.all
    @manufacturingstatus = ManufacturingStatus.find(params[:manufacturingstatus])
    @remaining = @manufacturingstatus.production_remaining.to_i
    
    @csn = @manufacturingstatus.cigarette_shred_number.to_i
    @sbn = @manufacturingstatus.small_box_number.to_i
    @prn = @manufacturingstatus.paper_roll_number.to_i
    @fn = @manufacturingstatus.filter_number.to_i
  end
  
  def update
    @manufacturingstatus = ManufacturingStatus.find(params[:id])
    
    production_remaining =  @manufacturingstatus.production_remaining.to_i + params[:manufacturing_status][:production_remaining].to_i
    @manufacturingstatus.production_remaining = production_remaining

    csn =  @manufacturingstatus.cigarette_shred_number.to_i + params[:manufacturing_status][:cigarette_shred_number].to_i
    @manufacturingstatus.cigarette_shred_number = csn

    prn =  @manufacturingstatus.paper_roll_number.to_i + params[:manufacturing_status][:paper_roll_number].to_i
    @manufacturingstatus.paper_roll_number = prn
    
    sbn =  @manufacturingstatus.small_box_number.to_i + params[:manufacturing_status][:small_box_number].to_i
    @manufacturingstatus.small_box_number = sbn

    fn =  @manufacturingstatus.filter_number.to_i + params[:manufacturing_status][:filter_number].to_i
    @manufacturingstatus.filter_number = fn

    @manufacturingstatus.save
    redirect_back(fallback_location: root_path)
  end

  private
  def manufacturingstatus_params
    params.require(:manufacturing_status).permit(:brand_id, :production_plan, :production_remaining, :cigarette_shred_number, :small_box_number, :paper_roll_number, :filter_number)
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def index
  end
end

app/controllers/paper_rolls_controller.rb
class PaperRollsController < ApplicationController
  def index
    @paper_rolls = PaperRoll.all
    @paper_roll = PaperRoll.new
  end

  def create
    @paper_roll = PaperRoll.create(paper_roll_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def paper_roll_params
    params.require(:paper_roll).permit(:name)
  end
end

app/controllers/small_boxes_controller.rb
class SmallBoxesController < ApplicationController
  def index
    @small_boxes = SmallBox.all
    @small_box = SmallBox.new
  end

  def create
    @small_box = SmallBox.create(small_box_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def small_box_params
    params.require(:small_box).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cigarette_shreds_helper.rb
module CigaretteShredsHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/manufacturing_statuses_helper.rb
module ManufacturingStatusesHelper
end

app/helpers/material_helper.rb
module MaterialHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/paper_rolls_helper.rb
module PaperRollsHelper
end

app/helpers/small_boxs_helper.rb
module SmallBoxsHelper
end

app/views/manufacturing_statuses/index.html.erb
<div class="wrapper">
  <h1>製造中銘柄状況</h1>
  <div class="production">
    <%= link_to "銘柄別使用材料一覧へ", brands_path %>
      <div class="production__path"></div>
    <%= link_to "材料を確認、登録する", materials_path %>
      <div class="production__path"></div>
    <%= link_to "製造計画追加", new_manufacturing_status_path %>
      <div class="production__path"></div>
    <h3>製造中の状況を見たい銘柄を選択して下さい<h3>
    <%= form_tag({controller: :manufacturing_statuses, action: :show, id: :[]}, {method: :get}) do %>
      <select name="manufacturingstatus">
        <%= @manufacturingstatuses.each do |n| %>
				  <option value=<%= n.id %>><%= n.brand.name %></option>
			  <% end %>
      </select>
      <input type="submit" value="銘柄を選択する">
    <% end %>
  </div>
</div>

app/views/manufacturing_statuses/new.html.erb
<div class="contents">
  <div class="container">
    <%= form_with(model: @manufacturingstatus, local: true) do |form| %>
      <h3>
        新規製造計画銘柄登録
      </h3>
      <%= form.label :name, "銘柄名" %>
      <%= form.collection_select :brand_id, Brand.all, :id, :name, placeholder: "銘柄名" %>
      <%= form.label :name, "製造予定数量" %>
      <%= form.number_field :production_plan, placeholder: "製造予定数量" %>c/s
      <%= form.label :name, "現製造数" %>
      <%= form.number_field :production_remaining, value: 0, placeholder: "製造数" %>
      <%= form.label :name, "初期材料数量" %>
      <%= form.label :name, "刻み" %>
      <%= form.number_field :cigarette_shred_number, value: 0, placeholder: "刻み" %>
      <%= form.label :name, "小箱" %>
      <%= form.number_field :small_box_number, value: 0, placeholder: "小箱" %>
      <%= form.label :name, "巻紙" %>
      <%= form.number_field :paper_roll_number, value: 0, placeholder: "巻紙" %>
      <%= form.label :name, "フィルター" %>
      <%= form.number_field :filter_number, value: 0, placeholder: "フィルター" %>
      <%= form.submit "登録する" %>
    <% end %>
  </div>
  <p>＊現製造数と初期材料数量は前回までの製造実績がない限りは０</p>
  <%= link_to "戻る", root_path %>
      <div class="production__path"></div>
</div>

app/views/manufacturing_statuses/show.html.erb
<div class = wrapper>
  <h1>製造中銘柄状況</h1>
  <div class = production>
    <%= link_to "銘柄別使用材料一覧へ", brands_path %>
      <div class = production__path></div>
    <%= link_to "材料を確認、登録する", materials_path %>
      <div class="production__path"></div>
    <%= link_to "製造計画追加", new_manufacturing_status_path %>
      <div class = production__path></div>
    <h3>製造管理状況を見たい銘柄を選択して下さい</h3>
    <%= form_tag({controller: :manufacturing_statuses, action: :show, id: :[]}, {method: :get}) do %>
      <select name="manufacturingstatus">
        <%= @manufacturingstatuses.each do |n| %>
				  <option value=<%= n.id %>><%= n.brand.name %></option>
			  <% end %>
      </select>
      <input type="submit" value="銘柄を選択する">
    <% end %>
    <div class = production__brand_name>
      <p>銘柄名</p>
      <h3 class = brand__name><%= @manufacturingstatus.brand.name %></h3>
    </div>
    <div class = production__statu>
      <div class = production__statu__plan>計画製造数
        <div class = production__statu__plan-number><%= @manufacturingstatus.production_plan %>c/s</div>
      </div>
      <div class = production__statu__remaining-number>製造数量
        <div class = production__statu__remaining><%= @manufacturingstatus.production_remaining %>c/s</div>
        <%= form_with(model: @manufacturingstatus, url: manufacturing_status_path(@manufacturingstatus.id), method: :patch, local: true) do |form| %>
          <%= form.number_field :production_remaining, value: "", placeholder: "製造数の追加" %>
          <%= form.submit "追加する"%>
        <% end %>
      </div>
    </div>
  </div>
  <div class = material__contents>
    <div class = material__title>
      <h3>供給材料状況</h3>
      <%= form_with(model: @manufacturingstatus, url: manufacturing_status_path(@manufacturingstatus.id), method: :patch, local: true) do |form| %>
        <table class = material__title__table>
          <tr>
            <th>材料名</th>
            <th>供給量</th>
            <th>供給したい数</th>
          <tr>
            <td>刻み</td>
            <td><%= @manufacturingstatus.cigarette_shred_number %>kg</td>
            <td>
              <%= form.number_field :cigarette_shred_number, value: "", placeholder: "供給数の追加" %>kg
              <%= form.submit "刻みを追加する"%>
            </td>
            <td>判定</td>
            <td>
              <% if @csn*5 >= @remaining %>
                <p class = "Judgment_true">足りてます。</p>
              <% else %>
                <p class = "Judgment_false">足りません。</p>
              <% end %>
            </td>
          </tr>
          <tr>
            <td colspan="5">＊製造数量に対して、刻みは1kgにつき、5c/s作れます。</td>
          </tr>
          <tr></tr>
          <tr></tr>
          <tr>
            <td>巻紙</td>
            <td><%= @manufacturingstatus.paper_roll_number %>巻</td>
            <td>
              <%= form.number_field :paper_roll_number, value: "", placeholder: "供給数の追加" %>巻
              <%= form.submit "巻紙を追加する"%>
            </td>
            <td>判定</td>
            <td>
              <% if @prn*10 >= @remaining %>
                <p class = "Judgment_true">足りてます。</p>
              <% else %>
                <p class = "Judgment_false">足りません。</p>
              <% end %>
            </td>
          </tr>
          <tr>
            <td colspan="5">＊製造数量に対して、巻紙は1巻につき、10c/s作れます。</td>
          </tr>
          <tr></tr>
          <tr></tr>
          <tr>
            <td>小箱</td>
            <td><%= @manufacturingstatus.small_box_number %>束</td>
            <td>
              <%= form.number_field :small_box_number, value: "", placeholder: "供給数の追加" %>束
              <%= form.submit "小箱を追加する"%>
            </td>
            <td>判定</td>
            <td>
              <% if @sbn >= @remaining %>
                <p class = "Judgment_true">足りてます。</p>
              <% else %>
                <p class = "Judgment_false">足りません。</p>
              <% end %>
            </td>
          </tr>
          <tr>
            <td colspan="5">＊製造数量に対して、小箱は1束につき、1c/s作れます。</td>
          </tr>
          <tr></tr>
          <tr></tr>
          <tr>
            <td>フィルター</td>
            <td><%= @manufacturingstatus.filter_number %>束</td>
            <td>
              <%= form.number_field :filter_number, value: "", placeholder: "供給数の追加" %>束
              <%= form.submit "フィルターを追加する"%>
            </td>
            <td>判定</td>
            <td>
              <% if @fn*5 >= @remaining %>
                <p class = "Judgment_true">足りてます。</p>
              <% else %>
                <p class = "Judgment_false">足りません。</p>
              <% end %>
            </td>
          </tr>
          <tr>
            <td colspan="5">＊製造数量に対して、フィルターは1箱につき、5c/s作れます。</td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>