config/routes.rb
Rails.application.routes.draw do
  root "manufacturing_statuses#index"
  resources :manufacturing_statuses, only: [:index, :new, :create, :show, :update] do
  end
  resources :brands, only: [:index, :new, :create] do
    collection do
      get 'search'
    end
  end
  resources :materials, only: [:index] do
  end
  resources :cigarette_shreds, only: [:index, :new, :create] do
  end
  resources :paper_rolls, only: [:index, :new, :create] do
  end
  resources :small_boxes, only: [:index, :new, :create] do
  end
  resources :filters, only: [:index, :new, :create] do
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :cigarette_shred
  belongs_to :small_box
  belongs_to :paper_roll
  belongs_to :filter
  has_many :manufacturing_statuses

  def self.search(search)
    if search
      Brand.where('name LIKE(?)', "#{search}%")
      #Brand.where(['name LIKE ? OR cigarette_shred_id LIKE ? OR paper_roll_id LIKE ? OR small_box_id LIKE ? OR filter_id  LIKE ?', "#{search}%", "#{search}%", "#{search}%", "#{search}%", "#{search}%"])
    else
      Brand.all
    end
  end
end

app/models/cigarette_shred.rb
class CigaretteShred < ApplicationRecord
  has_many :brands
end

app/models/filter.rb
class Filter < ApplicationRecord
  has_many :brands
end

app/models/manufacturing_status.rb
class ManufacturingStatus < ApplicationRecord
  belongs_to :brand
end

app/models/paper_roll.rb
class PaperRoll < ApplicationRecord
  has_many :brands
end

app/models/small_box.rb
class SmallBox < ApplicationRecord
  has_many :brands
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    Brand.create(brand_params)
    redirect_to brands_path
  end

  def search
    @brands = Brand.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end

  def brand_params
    params.require(:brand).permit(:name, :cigarette_shred_id, :small_box_id, :paper_roll_id, :filter_id)
  end
end

app/controllers/cigarette_shreds_controller.rb
class CigaretteShredsController < ApplicationController
  def index
    @cigarette_shreds = CigaretteShred.all
    @cigarette_shred = CigaretteShred.new
  end

  def create
    @cigarette_shred = CigaretteShred.create(cigarette_shred_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def cigarette_shred_params
    params.require(:cigarette_shred).permit(:name)
  end
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  def index
    @filters = Filter.all
    @filter = Filter.new
  end

  def create
    @filter = Filter.create(filter_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def filter_params
    params.require(:filter).permit(:name)
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def index
  end
end

app/controllers/paper_rolls_controller.rb
class PaperRollsController < ApplicationController
  def index
    @paper_rolls = PaperRoll.all
    @paper_roll = PaperRoll.new
  end

  def create
    @paper_roll = PaperRoll.create(paper_roll_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def paper_roll_params
    params.require(:paper_roll).permit(:name)
  end
end

app/controllers/small_boxes_controller.rb
class SmallBoxesController < ApplicationController
  def index
    @small_boxes = SmallBox.all
    @small_box = SmallBox.new
  end

  def create
    @small_box = SmallBox.create(small_box_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def small_box_params
    params.require(:small_box).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cigarette_shreds_helper.rb
module CigaretteShredsHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/manufacturing_statuses_helper.rb
module ManufacturingStatusesHelper
end

app/helpers/material_helper.rb
module MaterialHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/paper_rolls_helper.rb
module PaperRollsHelper
end

app/helpers/small_boxs_helper.rb
module SmallBoxsHelper
end

app/views/brands/index.html.erb
<div class = wrapper>
  <h1>銘柄別使用材料一覧</h1>
  <%= link_to "新規登録", new_brand_path %>
    <div class = brand_new_link>
  <%= link_to "製造状況ページへ", root_path %>
    <div class = manufacturing_link></div>
  <p>銘柄検索
    <%= form_with(url: search_brands_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "銘柄を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
  </p>
  <div class = brand__contents>
    <table class = brand__table>
      <thead>
        <tr class = brand__item>
          <td>銘柄名</td>
          <td>刻み</td>
          <td>巻紙</td>
          <td>小箱</td>
          <td>フィルター</td>
        </tr>
      </thead>
      <tbody class = brand__content>
        <% @brands.each do |brand| %>
          <tr class = brand__tr>
            <td><%= brand.name%></td>
            <td><%= CigaretteShred.find(brand.cigarette_shred_id).name %></td>
            <td><%= PaperRoll.find(brand.paper_roll_id).name%></td>
            <td><%= SmallBox.find(brand.small_box_id).name%></td>
            <td><%= Filter.find(brand.filter_id).name%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/brands/new.html.erb
<div class="contents">
  <div class="container">
    <%= form_with(model: @brand, local: true) do |form| %>
      <h3>
        銘柄新規登録
      </h3>
      <%= form.text_field :name, placeholder: "銘柄名" %>
      <%= form.collection_select :cigarette_shred_id, CigaretteShred.all, :id, :name, placeholder: "刻み" %>
      <%= form.collection_select :small_box_id, SmallBox.all, :id, :name, placeholder: "小箱" %>
      <%= form.collection_select :paper_roll_id, PaperRoll.all, :id, :name, placeholder: "巻紙" %>
      <%= form.collection_select :filter_id, Filter.all, :id, :name, placeholder: "フィルター" %>
      <%= form.submit "登録する" %>
    <% end %>
  </div>
  <%= link_to "戻る", root_path %>
      <div class="production__path"></div>
</div>

app/views/brands/search.html.erb
<div class = wrapper>
  <h1>材料一覧</h1>
  <%= link_to "新規登録", new_brand_path %>
    <div class = brand_new_link>
  <%= link_to "製造状況ページへ", root_path %>
    <div class = manufacturing_link></div>
  <div>検索</div>
    <%= form_with(url: search_brands_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "銘柄を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
  <div class = brand__contents>
    <table class = brand__table>
    　<thead>
        <tr class = brand__item>
          <td>銘柄名</td>
          <td>刻み</td>
          <td>巻紙</td>
          <td>小箱</td>
          <td>フィルター</td>
        </tr>
　　　 </thead>
      <tbody class = brand__content>
        <% @brands.each do |brand| %>
          <tr class = brand__tr >
            <td><%= brand.name%></td>
            <td><%= CigaretteShred.find(brand.cigarette_shred_id).name %></td>
            <td><%= PaperRoll.find(brand.paper_roll_id).name%></td>
            <td><%= SmallBox.find(brand.small_box_id).name%></td>
            <td><%= Filter.find(brand.filter_id).name%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>