config/routes.rb
Rails.application.routes.draw do
  root "manufacturing_statuses#index"
  resources :manufacturing_statuses, only: [:index, :new, :create, :show, :update] do
  end
  resources :brands, only: [:index, :new, :create] do
    collection do
      get 'search'
    end
  end
  resources :materials, only: [:index] do
  end
  resources :cigarette_shreds, only: [:index, :new, :create] do
  end
  resources :paper_rolls, only: [:index, :new, :create] do
  end
  resources :small_boxes, only: [:index, :new, :create] do
  end
  resources :filters, only: [:index, :new, :create] do
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :cigarette_shred
  belongs_to :small_box
  belongs_to :paper_roll
  belongs_to :filter
  has_many :manufacturing_statuses

  def self.search(search)
    if search
      Brand.where('name LIKE(?)', "#{search}%")
      #Brand.where(['name LIKE ? OR cigarette_shred_id LIKE ? OR paper_roll_id LIKE ? OR small_box_id LIKE ? OR filter_id  LIKE ?', "#{search}%", "#{search}%", "#{search}%", "#{search}%", "#{search}%"])
    else
      Brand.all
    end
  end
end

app/models/cigarette_shred.rb
class CigaretteShred < ApplicationRecord
  has_many :brands
end

app/models/filter.rb
class Filter < ApplicationRecord
  has_many :brands
end

app/models/manufacturing_status.rb
class ManufacturingStatus < ApplicationRecord
  belongs_to :brand
end

app/models/paper_roll.rb
class PaperRoll < ApplicationRecord
  has_many :brands
end

app/models/small_box.rb
class SmallBox < ApplicationRecord
  has_many :brands
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    Brand.create(brand_params)
    redirect_to brands_path
  end

  def search
    @brands = Brand.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end

  def brand_params
    params.require(:brand).permit(:name, :cigarette_shred_id, :small_box_id, :paper_roll_id, :filter_id)
  end
end

app/controllers/cigarette_shreds_controller.rb
class CigaretteShredsController < ApplicationController
  def index
    @cigarette_shreds = CigaretteShred.all
    @cigarette_shred = CigaretteShred.new
  end

  def create
    @cigarette_shred = CigaretteShred.create(cigarette_shred_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def cigarette_shred_params
    params.require(:cigarette_shred).permit(:name)
  end
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  def index
    @filters = Filter.all
    @filter = Filter.new
  end

  def create
    @filter = Filter.create(filter_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def filter_params
    params.require(:filter).permit(:name)
  end
end

app/controllers/manufacturing_statuses_controller.rb
class ManufacturingStatusesController < ApplicationController
  def index
    @manufacturingstatuses = ManufacturingStatus.all
  end

  def new
    @manufacturingstatus = ManufacturingStatus.new
  end

  def create
    @manufacturingstatus = ManufacturingStatus.create(manufacturingstatus_params)
    redirect_to root_path
  end

  def show
    @manufacturingstatuses = ManufacturingStatus.all
    @manufacturingstatus = ManufacturingStatus.find(params[:manufacturingstatus])
    @remaining = @manufacturingstatus.production_remaining.to_i
    
    @csn = @manufacturingstatus.cigarette_shred_number.to_i
    @sbn = @manufacturingstatus.small_box_number.to_i
    @prn = @manufacturingstatus.paper_roll_number.to_i
    @fn = @manufacturingstatus.filter_number.to_i
  end
  
  def update
    @manufacturingstatus = ManufacturingStatus.find(params[:id])
    
    production_remaining =  @manufacturingstatus.production_remaining.to_i + params[:manufacturing_status][:production_remaining].to_i
    @manufacturingstatus.production_remaining = production_remaining

    csn =  @manufacturingstatus.cigarette_shred_number.to_i + params[:manufacturing_status][:cigarette_shred_number].to_i
    @manufacturingstatus.cigarette_shred_number = csn

    prn =  @manufacturingstatus.paper_roll_number.to_i + params[:manufacturing_status][:paper_roll_number].to_i
    @manufacturingstatus.paper_roll_number = prn
    
    sbn =  @manufacturingstatus.small_box_number.to_i + params[:manufacturing_status][:small_box_number].to_i
    @manufacturingstatus.small_box_number = sbn

    fn =  @manufacturingstatus.filter_number.to_i + params[:manufacturing_status][:filter_number].to_i
    @manufacturingstatus.filter_number = fn

    @manufacturingstatus.save
    redirect_back(fallback_location: root_path)
  end

  private
  def manufacturingstatus_params
    params.require(:manufacturing_status).permit(:brand_id, :production_plan, :production_remaining, :cigarette_shred_number, :small_box_number, :paper_roll_number, :filter_number)
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def index
  end
end

app/controllers/paper_rolls_controller.rb
class PaperRollsController < ApplicationController
  def index
    @paper_rolls = PaperRoll.all
    @paper_roll = PaperRoll.new
  end

  def create
    @paper_roll = PaperRoll.create(paper_roll_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def paper_roll_params
    params.require(:paper_roll).permit(:name)
  end
end

app/controllers/small_boxes_controller.rb
class SmallBoxesController < ApplicationController
  def index
    @small_boxes = SmallBox.all
    @small_box = SmallBox.new
  end

  def create
    @small_box = SmallBox.create(small_box_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def small_box_params
    params.require(:small_box).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cigarette_shreds_helper.rb
module CigaretteShredsHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/manufacturing_statuses_helper.rb
module ManufacturingStatusesHelper
end

app/helpers/material_helper.rb
module MaterialHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/paper_rolls_helper.rb
module PaperRollsHelper
end

app/helpers/small_boxs_helper.rb
module SmallBoxsHelper
end

app/views/cigarette_shreds/index.html.erb
<div class = wrapper>
  <h1>刻み</h1>
  <%= link_to "製造状況ページへ", root_path %>
    <div class = manufacturing_link></div>
  <h2>新規材料登録</h2>
  <%= form_with(model: @cigarette_shred, local: true, method: :post, class: "material-form") do |form| %>
    <%= form.text_field :name, placeholder: "材料名を入力して下さい", class: "material-input" %>
    <%= form.submit "追加する"%>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>NO</th>
        <th></th>
        <th></th>
        <th></th>
        <th>材料名</th>
      </tr>
    </thead>
    <tbody>
      <% @cigarette_shreds.each do |cigarette_shred| %>
        <tr>
          <td class="material__show"><%= cigarette_shred.id%></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="material__show"><%= cigarette_shred.name%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/filters/index.html.erb
<div class = wrapper>
  <h1>フィルター</h1>
  <%= link_to "製造状況ページへ", root_path %>
    <div class = manufacturing_link></div>
  <h2>新規材料登録</h2>
  <%= form_with(model: @filter, local: true, method: :post, class: "material-form") do |form| %>
    <%= form.text_field :name, placeholder: "材料名を入力して下さい", class: "material-input" %>
    <%= form.submit "追加する"%>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>NO</th>
        <th></th>
        <th></th>
        <th></th>
        <th>材料名</th>
      </tr>
    </thead>
    <tbody>
      <% @filters.each do |filter| %>
        <tr>
          <td class="material__show"><%= filter.id%></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="material__show"><%= filter.name%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/materials/index.html.erb
<div class = wrapper>
  <h1>登録、確認したい材料を選択して下さい</h1>
  <%= link_to "刻み", cigarette_shreds_path %>
    <div class="material__path"></div>
  <%= link_to "巻紙", paper_rolls_path %>
    <div class="material__path"></div>
  <%= link_to "小箱", small_boxes_path %>
    <div class="material__path"></div>
  <%= link_to "フィルター", filters_path %>
    <div class="material__path"></div>
</div>

app/views/paper_rolls/index.html.erb
<div class = wrapper>
  <h1>巻紙</h1>
  <%= link_to "製造状況ページへ", root_path %>
    <div class = manufacturing_link></div>
  <h2>新規材料登録</h2>
  <%= form_with(model: @paper_roll, local: true, method: :post, class: "material-form") do |form| %>
    <%= form.text_field :name, placeholder: "材料名を入力して下さい", class: "material-input" %>
    <%= form.submit "追加する"%>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>NO</th>
        <th></th>
        <th></th>
        <th></th>
        <th>材料名</th>
      </tr>
    </thead>
    <tbody>
      <% @paper_rolls.each do |paper_roll| %>
        <tr>
          <td class="material__show"><%= paper_roll.id%></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="material__show"><%= paper_roll.name%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/small_boxes/index.html.erb
<div class = wrapper>
  <h1>小箱</h1>
  <%= link_to "製造状況ページへ", root_path %>
    <div class = manufacturing_link></div>
  <h2>新規材料登録</h2>
  <%= form_with(model: @small_box, local: true, method: :post, class: "material-form") do |form| %>
    <%= form.text_field :name, placeholder: "材料名を入力して下さい", class: "material-input" %>
    <%= form.submit "追加する"%>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>NO</th>
        <th></th>
        <th></th>
        <th></th>
        <th>材料名</th>
      </tr>
    </thead>
    <tbody>
      <% @small_boxes.each do |small_box| %>
        <tr>
          <td class="material__show"><%= small_box.id%></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="material__show"><%= small_box.name%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>